[package]
name = "vfs"
version = "0.1.0"
edition = "2021"
description = "A Virtual File System, for making support for other file systems"
license = "MIT"
publish = false

[dependencies]
#mio = { path = "../../mm/mio/" }
memory = { path = "../../mm/memory/" }
