[package]
name = "init"
version = "0.1.0"
edition = "2018"
description = "Main kernel initialization"

[target.'cfg(target_arch = "x86_64")'.dependencies]
pc_keyboard = { path = "../drivers/input/keyboard/pc_keyboard/" }
ps2_mouse = { path = "../drivers/input/mouse/ps2_mouse/" }
vgag = { path = "../drivers/gpu/vgag/" }

[dependencies]
cfg-if = "1.0.0"
kinfo = { path = "../kernel/kinfo/" }
konfig = { path = "../kernel/konfig/", features = ["default_config"] }
lazy_static = "1.4.0"
modules = { path = "../kernel/modules/" }
novuskinc = { path = "../include/novusk/" }
printk = { path = "../kernel/printk/" }
spin = { version = "0.9.2", features = ["spin_mutex"] }
