[package]
name = "sf_rpilcd_35"
version = "0.1.0"
edition = "2021"
description = "Support for the SunFounder RaspberryPi 3.5in display"

[dependencies]
novuskinc = { path = "../../../../include/novusk/" }
rpi = { path = "../../../rpi/" }

