[package]
name = "os_example"
version = "0.1.0"
authors = ["Nathan McMillan <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
libnu = "0.1.1"
uefi = "0.8.1"

[target.'cfg(target_arch = "x86_64")']
[dependencies.x86]
path = "../../arch/x86/"
features = ["default_machine"]
