[package]
name = "vgag"
version = "0.1.0"
edition = "2021"
description = "Vga graphics driver"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
libcolor = { path = "../../../lib/libcolor/" }
novuskinc = { path = "../../../include/novusk/", features = ["library"] }
printk = { path = "../../../kernel/printk/" }
spin = "0.9.2"
volatile = "0.2.7"

[features]
default = []
no_panic = []
