[package]
name = "stm_eth"
version = "0.1.0"
edition = "2021"
description = "Ethernet driver for STM32 devices"
license = "MIT"
publish = false

[dependencies]
ethernet = { path = "../../../drivers/net/ethernet/" }
novuskinc = { path = "../../../include/novusk/" }
stm32-eth = { version = "0.2.0" }

[features]
unsupported_stm32fxxx = ["stm32-eth/stm32f407"]
stm32f407 = ["stm32-eth/stm32f407"]
