[package]
name = "rpi"
version = "0.1.0"
edition = "2018"
description = ""

[dependencies]
io = { path = "../../mm/io/" }
kinfo = { path = "../../kernel/kinfo/" }
libbmu = { path = "../../lib/libbmu/" }
novuskinc = { path = "../../include/novusk/" }
printk = { path = "../../kernel/printk/" }
tock-registers = "0.7.0"
