[package]
name = "bcm_soc"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
cpu = { path = "../" }
novuskinc = { git = "https://github.com/new-kernel/novuskinc/" }
tock-registers = "0.8.1"

[features]
bcm2837 = []
