[package]
name = "printk"
version = "0.1.0"
edition = "2021"
description = "Kernel printing function and macro"

[lib]
name = "printk"
edition = "2021"
path = "src/lib.rs"

[dependencies]
novuskinc = { path = "../../include/novusk/" }
