[package]
name = "device"
version = "0.1.0"
edition = "2021"
description = "Traits for device specific drivers"
license = "MIT"
publish = false

[dependencies]
dif = "0.1.1"
novuskinc = { git = "https://github.com/new-kernel/novuskinc/", features = ["v3"] }

[features]
dif_alloc = ["dif/alloc"]
