[package]
name = "sos"
version = "0.1.0"
edition = "2021"
description = "Starts Novusk based OSes"

[dependencies]
fom_os = { path = "../fom_os/" }
libost = { path = "../../lib/libost" }
printk = { path = "../../kernel/printk/" }
