[package]
name = "drivers"
version = "0.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[dependencies]
arch = { path = "../arch/" }
novusk_lib = { path = "../lib/" }
pc-keyboard = "0.5.1"