[package]
name = "bootloader_image"
version = "0.1.0"
edition = "2021"
description = "Links x86_64 Novusk with bootloader v0.10+"
license = "MIT"
publish = false

[dependencies]
bootloader-locator = "0.0.4"
