[package]
name = "stellarisd"
version = "0.1.0"
edition = "2021"
description = "Board support for Stellaris boards"

[dependencies]
cortex-m = "0.7.3"
cortex-m-semihosting = "0.3.7"
device = { path = "../../../device/" }
libbmu = { path = "../../../../lib/libbmu/" }
novuskinc = { path = "../../../../include/novusk/" }
tm4c123x-hal = "0.10.2"

[features]
default = []
stellaris_6965 = []
